import "../globals.css";
import React from "react";

import Header from "../components/ClientHeader";
import Footer from "../components/Footer";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ClientLayout({ children }) {
  return (
    <main className="flex-1">
      <Header />
      <section className="flex flex-col min-h-screen w-screen bg-gray-100 mt-4">
        

        {/* Contenu principal qui prend l'espace restant */}
        <div className="">
          {children}
        </div>

        {/* Footer toujours en bas */}
        <Footer />
      </section>
    </main>
  );
}