import "./globals.css";
import React from "react";
import { AuthProvider } from "./context/AuthContext";
import Header from "./components/ClientHeader";
import Footer from "./components/Footer";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        
        <AuthProvider>
      
          <div className="">

          
          {children}
          </div>
      
        </AuthProvider>
  
      </body>
    </html>
  );
}
